---
- name: Compliance Verification Script v0.3
  hosts: localhost
  vars_files:
    - vars_files/engine.yml
    - vars_files/hosts.yml

  pre_tasks:
    - name: Ensure dependencies are met
      include_role:
        name: dependency_checker
      vars:
        os_flavor: ansible_facts["ansible_distribution_file_variety"]

    - name: Authenticate against oVirt engine
      ovirt.ovirt.ovirt_auth:
        url: "{{ engine_url }}/ovirt-engine/api"
        username: "{{ engine_username }}"
        password: "{{ engine_password }}"
        insecure: yes

  roles:
    - role: base_info
    - role: fips_140_2
      fips_prod_type: "{{ hostvars[inventory_hostname]['prod_type'] }}"
      fips_parsed_os_release: "{{ hostvars[inventory_hostname]['parsed_os_release'] }}"
      fips_groups: "{{ hostvars[inventory_hostname]['groups']['hosts'] }}"
      fips_host_username: "{{ host_username }}"
      fips_num_hosts: |
        {{ num_hosts }}
      when: check_fips|default(false)
    - role: disa_stig
      when: check_disa_stig|default(false)
    - role: common_criteria
      when: check_common_criteria|default(false)

  post_tasks:
    - name: Revoke SSO token
      ovirt.ovirt.ovirt_auth:
        ovirt_auth: "{{ ovirt_auth }}"
        state: absent
